apiVersion: apps/v1
kind: Deployment
metadata:
  name: openlabdashboardfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openLabDashboard
  template:
    metadata:
      labels:
        app: openLabDashboard
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: openlabdashboardfrontend
        image: openlabdashboardregistry.azurecr.io/openlabdashboardfrontend:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 8080
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: openlabdashboardfrontend
spec:
  ports:
  - port: 80
  selector:
    app: openLabDashboard
